name: Daily UI/API Test Run

on:
  workflow_dispatch: 
  schedule:
    - cron: '30 5 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Action to set up the Node.js environment
        with:
          node-version: '22' 

      - name: Install dependencies
        run: npm install # Install project dependencies as defined in package.json

      - name: Create .env file with secrets
        run: |
          echo "RUDDERSTACK_USERNAME=${{ secrets.RUDDERSTACK_USERNAME }}" > .env
          echo "RUDDERSTACK_PASSWORD=${{ secrets.RUDDERSTACK_PASSWORD }}" >> .env
          echo "RUDDERSTACK_BASE_URL=${{ secrets.RUDDERSTACK_BASE_URL || 'https://app.rudderstack.com' }}" >> .env
        env:
          RUDDERSTACK_USERNAME: ${{ secrets.RUDDERSTACK_USERNAME }}
          RUDDERSTACK_PASSWORD: ${{ secrets.RUDDERSTACK_PASSWORD }}
          RUDDERSTACK_BASE_URL: ${{ secrets.RUDDERSTACK_BASE_URL }} 

      - name: Run WebdriverIO Tests
        run: npx wdio --host localhost 

      - name: Upload Allure Report Results
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: allure-results 
          path: allure-results 
          retention-days: 7 